server:
  port: 8006

spring:
  application:
    name: consul-provider-payment
  #consul注册中心地址
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        enabled: true
        # 使用 consul 服务器 IP, 而不是 hostname, 需要搭配 prefer-ip-address 属性
        ip-address: 127.0.0.1
        # 在注册时使用 consul IP, 而不是 hostname
        prefer-ip-address: true
        health-check-url: http://${spring.cloud.consul.host}:${server.port}/actuator/health
        service-name: ${spring.application.name}
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 648340618

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.jtr.entriy

