server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com
  client:
    #自己不检索自己，自己是server，所以不需要检索自己
    fetch-registry: false
    #自己不注册自己
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/